<def f='linux-5.3.1/arch/x86/mm/extable.c' l='51' ll='93' type='bool ex_handler_refcount(const struct exception_table_entry * fixup, struct pt_regs * regs, int trapnr, unsigned long error_code, unsigned long fault_addr)'/>
<dec f='linux-5.3.1/arch/x86/mm/extable.c' l='94' type='bool ex_handler_refcount(const struct exception_table_entry * , struct pt_regs * , int , unsigned long , unsigned long )'/>
<use f='linux-5.3.1/arch/x86/mm/extable.c' l='94' c='ex_handler_refcount'/>
<use f='linux-5.3.1/arch/x86/mm/extable.c' l='94' u='a'/>
<doc f='linux-5.3.1/arch/x86/mm/extable.c' l='47'>/*
 * Handler for UD0 exception following a failed test against the
 * result of a refcount inc/dec/add/sub.
 */</doc>
